### ISSUE TITLE
font

### ISSUE THREAD

**Issue by Kaii-h** [Geordan9/GeoArcSysHIPTool#1]
The program works great. And there is a question close to the HIP format. 
Do you know how the font is encoded in "font.abc"? For later linking with "font.hip". 
In ".abc" I found X Y coordinates with width and height, and one more duplicate coordinates. Changing them changes the display of letters.
But how the game looks at unicode letters in "string.atf" and interprets them in ".abc" to find the letter in ".hip" is a mystery.

**Comment by RealApxu** [comment]
The first chunk of bytes (right after 24-byte header) contains marks for the unicode table, where "00 00" - "symbol is unused", other value - "use the symbol" and what number it is in the font texture.
Something like that
![1](https://user-images.githubusercontent.com/45734287/121768275-d09ba800-cba0-11eb-94d8-acf732ef36d0.png)

**Comment by Kaii-h** [comment]
> (right after 24-byte header)
Right on target, only if the account is 0100 and not 0001.
> unicode table
After that, the puzzle almost came together.
I.e., to add letters of another alphabet I, for example, for Russian, must skip 2080 bytes after the header in the decimal and add some characters to this pair (which is confirmed in another font.abc where they are already from BBCF or BBCSE where there is Д). Any characters that won't be a repetition?
And then how? Add 24-byte and 32-byte coordinates in two places?
And what about the header? Can it be left untouched?
And with the picture of the font letters. Can a different resolution be used? Other than 512x512 or 4096x4096 or 512x1024.

**Comment by RealApxu** [comment]
> Right on target, only if the account is 0100 and not 0001.

Oh, yeah, I used the file from PS3 P4U for example, which is big-endian, BlazBlue on PC have files in little-endian. I should've clarified that.

> I.e., to add letters of another alphabet I, for example, for Russian, must skip 2080 bytes after the header in the decimal and add some characters to this pair (which is confirmed in another font.abc where they are already from BBCF or BBCSE where there is Д). Any characters that won't be a repetition?

Yes, I've done exactly that. Changed the "00 00" on that position to the appropriate value (I'll call it "XX XX"). But numbers must be strictly in ascending order. You will need to change following values if there are any.

> Or it's the order in the picture with the font letters.
And then how? Add 24-byte and 32-byte coordinates in two places?

Yes. Add new values to the second and third tables on the "XX XX" positions.  Order in texture file is not important, you can add new letters after the existing symbols.

>And what about the header? Can it be left untouched?
And with the picture of the font letters. Can a different resolution be used? Other than 512x512 or 4096x4096 or 512x1024.

Haven't checked that. Header contains the code of the last unicode letter used in font ("FF 34" on the pic). It may be changed if needed. There is also value which depends on texture resolution, but I'm not sure about that. ("42 24 00 00" on the pic, written two times)

**Comment by Kaii-h** [comment]
Thank you. It works as it should and it doesn't crash. All that remains is to rewrite the new coordinates into the font. _Which will take some time..._
>  last unicode letter used in font ("FF 34"

It is not the last character in Unicode, but how many bytes this block with the Unicode character selection occupies. Only for some reason it is backwards and offset by 1 byte.
If don't change it, the game crashes.

Also changed font image from 4096x4096 to 4096x232 and it displays as it should (and hopefully will continue). What the other bytes are responsible for in the header is unclear. Maybe if vice versa, to enlarge the image - it can not recognize.

**Comment by RealApxu** [comment]
You are welcome!

> It is not the last character in Unicode, but how many bytes this block with the Unicode character selection occupies. Only for some reason it is backwards and offset by 1 byte.

I meant something similar. I guess my English let me down. Or maybe it's different between games.

**Comment by Geordan9** [comment]
Very insightful. Since the conversation looks like it concluded and the subject isn't related to the my tool's purpose, I'll close the issue here.
